language: python
os: osx
python:
  - "2.7"
# command to install dependencies
install:
#  - pip install -r reference/requirements.txt
  - "pip install flake8"
# command to run tests

script:
  - "flake8 ."